homeassistant:
  name: Home
  latitude: 0.0
  longitude: 0.0
  elevation: 0
  unit_system: metric
  time_zone: UTC

# Logger configuration
logger:
  default: info
  logs:
    custom_components.linja_priser: debug

# Enable the custom component
sensor:
  - platform: linja_priser
    api_key: "your_api_key"
    metering_point_id: "your_metering_point_id"
    price_type: "energy_price"
  - platform: linja_priser
    api_key: "your_api_key"
    metering_point_id: "your_metering_point_id"
    price_type: "fixed_price_per_hour"