name: Validate

on: [push, pull_request]

jobs:
  validate:
    name: Validate Home Assistant Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant

      - name: Validate configuration
        run: |
          hass --script check_config --config . --info all